# Generated by Django 5.2.5 on 2025-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed_work",
            field=models.FileField(blank=True, null=True, upload_to="completed_work/"),
        ),
    ]
